package com.login;

import java.awt.Color;

public class Login extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        logoname = new javax.swing.JLabel();
        citybg = new javax.swing.JLabel();
        cabecalho = new javax.swing.JPanel();
        jp_BotaoSaida = new javax.swing.JPanel();
        jl_TextoSaida = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        jl_TituloIniciarSessao = new javax.swing.JLabel();
        jl_TituloUsuario = new javax.swing.JLabel();
        jtf_CampoUsuario = new javax.swing.JTextField();
        js_SeparadorUsuario = new javax.swing.JSeparator();
        jl_TituloSenha = new javax.swing.JLabel();
        jpf_CampoSenha = new javax.swing.JPasswordField();
        js_SeparadorSenha = new javax.swing.JSeparator();
        jp_Botao = new javax.swing.JPanel();
        jl_TextoBotao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png"))); // NOI18N
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 290, 140));

        logoname.setBackground(new java.awt.Color(255, 255, 255));
        logoname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoname.setForeground(new java.awt.Color(255, 255, 255));
        logoname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoname.setText("EMPRESA");
        bg.add(logoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 290, -1));

        citybg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city.png"))); // NOI18N
        bg.add(citybg, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 500));

        cabecalho.setBackground(new java.awt.Color(255, 255, 255));
        cabecalho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cabecalhoMouseDragged(evt);
            }
        });
        cabecalho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cabecalhoMousePressed(evt);
            }
        });

        jp_BotaoSaida.setBackground(new java.awt.Color(255, 255, 255));
        jp_BotaoSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_BotaoSaida.setPreferredSize(new java.awt.Dimension(40, 40));

        jl_TextoSaida.setBackground(new java.awt.Color(0, 0, 0));
        jl_TextoSaida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_TextoSaida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_TextoSaida.setText("X");
        jl_TextoSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_TextoSaidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_TextoSaidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_TextoSaidaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_BotaoSaidaLayout = new javax.swing.GroupLayout(jp_BotaoSaida);
        jp_BotaoSaida.setLayout(jp_BotaoSaidaLayout);
        jp_BotaoSaidaLayout.setHorizontalGroup(
            jp_BotaoSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_BotaoSaidaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_TextoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_BotaoSaidaLayout.setVerticalGroup(
            jp_BotaoSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_BotaoSaidaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_TextoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout cabecalhoLayout = new javax.swing.GroupLayout(cabecalho);
        cabecalho.setLayout(cabecalhoLayout);
        cabecalhoLayout.setHorizontalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoLayout.createSequentialGroup()
                .addComponent(jp_BotaoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 760, Short.MAX_VALUE))
        );
        cabecalhoLayout.setVerticalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jp_BotaoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(cabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        favicon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        favicon.setForeground(new java.awt.Color(0, 0, 0));
        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/favicon.png"))); // NOI18N
        bg.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 60, 120, -1));

        jl_TituloIniciarSessao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jl_TituloIniciarSessao.setForeground(new java.awt.Color(0, 0, 0));
        jl_TituloIniciarSessao.setText("INICIAR SESSÃO");
        bg.add(jl_TituloIniciarSessao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jl_TituloUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_TituloUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jl_TituloUsuario.setText("USUÁRIO");
        bg.add(jl_TituloUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jtf_CampoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jtf_CampoUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jtf_CampoUsuario.setText("Digite seu nome de usuário");
        jtf_CampoUsuario.setBorder(null);
        jtf_CampoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtf_CampoUsuarioMousePressed(evt);
            }
        });
        bg.add(jtf_CampoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 400, 20));
        bg.add(js_SeparadorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 263, 400, 10));

        jl_TituloSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_TituloSenha.setForeground(new java.awt.Color(0, 0, 0));
        jl_TituloSenha.setText("SENHA");
        bg.add(jl_TituloSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jpf_CampoSenha.setBackground(new java.awt.Color(255, 255, 255));
        jpf_CampoSenha.setForeground(new java.awt.Color(204, 204, 204));
        jpf_CampoSenha.setText("********");
        jpf_CampoSenha.setBorder(null);
        jpf_CampoSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpf_CampoSenhaMousePressed(evt);
            }
        });
        bg.add(jpf_CampoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 400, -1));
        bg.add(js_SeparadorSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 400, 10));

        jp_Botao.setBackground(new java.awt.Color(0, 134, 190));
        jp_Botao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_Botao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_BotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_BotaoMouseExited(evt);
            }
        });

        jl_TextoBotao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_TextoBotao.setForeground(new java.awt.Color(255, 255, 255));
        jl_TextoBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_TextoBotao.setText("ENTRAR");
        jl_TextoBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_TextoBotaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_BotaoLayout = new javax.swing.GroupLayout(jp_Botao);
        jp_Botao.setLayout(jp_BotaoLayout);
        jp_BotaoLayout.setHorizontalGroup(
            jp_BotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_TextoBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jp_BotaoLayout.setVerticalGroup(
            jp_BotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_TextoBotao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(jp_Botao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cabecalhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabecalhoMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_cabecalhoMousePressed

    private void cabecalhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabecalhoMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_cabecalhoMouseDragged

    private void jl_TextoSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_TextoSaidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jl_TextoSaidaMouseClicked

    private void jl_TextoSaidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_TextoSaidaMouseEntered
        jp_BotaoSaida.setBackground(Color.red);
        jl_TextoSaida.setForeground(Color.white);
    }//GEN-LAST:event_jl_TextoSaidaMouseEntered

    private void jl_TextoSaidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_TextoSaidaMouseExited
        jp_BotaoSaida.setBackground(Color.white);
        jl_TextoSaida.setForeground(Color.black);
    }//GEN-LAST:event_jl_TextoSaidaMouseExited

    private void jp_BotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BotaoMouseEntered
        jp_Botao.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_jp_BotaoMouseEntered

    private void jp_BotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BotaoMouseExited
        jp_Botao.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_jp_BotaoMouseExited

    private void jtf_CampoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_CampoUsuarioMousePressed
        if (jtf_CampoUsuario.getText().equals("Digite seu nome de usuário")) {
            jtf_CampoUsuario.setText("");
            jtf_CampoUsuario.setForeground(Color.black);
        }
        
        if (String.valueOf(jpf_CampoSenha.getPassword()).isEmpty()) {
            jpf_CampoSenha.setText("********");
            jpf_CampoSenha.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jtf_CampoUsuarioMousePressed

    private void jpf_CampoSenhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpf_CampoSenhaMousePressed
        if (String.valueOf(jpf_CampoSenha.getPassword()).equals("********")) {
            jpf_CampoSenha.setText("");
            jpf_CampoSenha.setForeground(Color.black);
        }
        if (jtf_CampoUsuario.getText().isEmpty()) {
            jtf_CampoUsuario.setText("Digite seu nome de usuário");
            jtf_CampoUsuario.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jpf_CampoSenhaMousePressed

    private void jl_TextoBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_TextoBotaoMouseClicked
        String senha = String.valueOf(jpf_CampoSenha.getPassword());
        if (jtf_CampoUsuario.getText().equals("adm") && jpf_CampoSenha.getText().equals("adm")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Bem-vindo ao sistema!", "Sucesso", javax.swing.JOptionPane.DEFAULT_OPTION);
            System.exit(0);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Dados incorretos.\nTente novamente.");
        }
    }//GEN-LAST:event_jl_TextoBotaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel cabecalho;
    private javax.swing.JLabel citybg;
    private javax.swing.JLabel favicon;
    private javax.swing.JLabel jl_TextoBotao;
    private javax.swing.JLabel jl_TextoSaida;
    private javax.swing.JLabel jl_TituloIniciarSessao;
    private javax.swing.JLabel jl_TituloSenha;
    private javax.swing.JLabel jl_TituloUsuario;
    private javax.swing.JPanel jp_Botao;
    private javax.swing.JPanel jp_BotaoSaida;
    private javax.swing.JPasswordField jpf_CampoSenha;
    private javax.swing.JSeparator js_SeparadorSenha;
    private javax.swing.JSeparator js_SeparadorUsuario;
    private javax.swing.JTextField jtf_CampoUsuario;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoname;
    // End of variables declaration//GEN-END:variables
}
